---
- name: Start IPAM and DNS servers
  hosts: localhost
  tasks:
    - name: Get a free IP from IPAM
      ipam_free_ip:
        api_url: "http://127.0.0.1:8000"
      register: ipam_result

    - name: Display IPAM result
      debug:
        msg: "{{ ipam_result }}"

    - name: Reserve IP
      ipam_reserve_ip:
        api_url: "http://127.0.0.1:8000"
        ip: "192.168.10.2"
        hostname: "host_44"
      register: result_ip

    - name: Display IPAM result
      debug:
        msg: "{{ result_ip }}"

    - name: Send POST request to manage_access endpoint
      manage_access:
        api_url: "http://127.0.0.1:8000"
        username: "abbas"
        password: "ajdjdjdjd"
      register: response

    - name: Print response
      debug:
        var: response.response
